<a href="https://colab.research.google.com/github/parthivz/Fundamentals-of-GenAI-Course-Lab/blob/main/PyTorch_1_Exercise_PyTorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import the __`torch`__ package

In [1]:
import torch as pt
pt.manual_seed(0);

## Create a vector of ten zeros

In [2]:
vector_zeros=pt.zeros(10)
vector_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Create a vector of size ten with nine zeros and a 1 in the fifth position

In [3]:
vector_custom=pt.zeros(10)
vector_custom[4]=1
vector_custom

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## Create a vector with values ranging from 10 to 49

In [4]:
vector_range=pt.arange(10,50)
vector_range

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49])

## Reverse the previous vector

In [6]:
vector_reversed = vector_range.flip(0)
vector_reversed

tensor([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
        31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
        13, 12, 11, 10])

## Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
matrix_3x3 = pt.arange(9).reshape(3, 3)
matrix_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

## Find the indices of the non-zero elements of the following array:

In [10]:
v = pt.tensor([1, 2, 0, 0, 4, 0]) # Given
v

tensor([1, 2, 0, 0, 4, 0])

In [11]:
non_zero_indices = pt.nonzero(v)
non_zero_indices

tensor([[0],
        [1],
        [4]])

## Create a 5x5 identity matrix

In [12]:
identity_matrix = pt.eye(5)
identity_matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Create a 3x3x3 array with random values

In [13]:
random_array= pt.rand(3,3,3)
random_array

tensor([[[0.4963, 0.7682, 0.0885],
         [0.1320, 0.3074, 0.6341],
         [0.4901, 0.8964, 0.4556]],

        [[0.6323, 0.3489, 0.4017],
         [0.0223, 0.1689, 0.2939],
         [0.5185, 0.6977, 0.8000]],

        [[0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742],
         [0.4194, 0.5529, 0.9527]]])

## Find the minimum and maximum values generated in the previous step

In [14]:
min_val=pt.min(random_array)
max_val=pt.max(random_array)
min_val,max_val

(tensor(0.0223), tensor(0.9527))

## Create a vector with 30 random values and find its mean

In [17]:
random_vector=pt.rand(30)
random_vector


tensor([0.2711, 0.6923, 0.2038, 0.6833, 0.7529, 0.8579, 0.6870, 0.0051, 0.1757,
        0.7497, 0.6047, 0.1100, 0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237,
        0.4910, 0.1235, 0.1143, 0.4725, 0.5751, 0.2952, 0.7967, 0.1957, 0.9537,
        0.8426, 0.0784, 0.3756])

In [18]:
mean_value=pt.mean(random_vector)
mean_value

tensor(0.4602)

## Create a 5x5 2d array with 1s around the edges and 0s in the middle

In [19]:
array_2d = pt.ones(5, 5)
array_2d[1:-1, 1:-1] = 0
array_2d

tensor([[1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1.]])

## Try to predict the output of each of the following cells before running them

In [20]:
0 * float('nan')

nan

In [21]:
float('nan') == float('nan')

False

In [22]:
float('inf') > float('nan')

False

In [23]:
float('nan') - float('nan')

nan

In [24]:
0.3 == 3 * 0.1

False

In [25]:
pt.tensor([0]) // pt.tensor([0]) #crashes the kernel :) continue with the next cell

RuntimeError: ZeroDivisionError

In [26]:
import torch as pt #this is in case you crashed on the previous cell
pt.tensor([0]) // pt.tensor([0.0])

tensor([nan])

In [27]:
nan_scalar = pt.tensor([float('nan')])

pt.isnan(nan_scalar)

tensor([True])

In [28]:
pt.tensor([0]) / pt.tensor([0.0])

tensor([nan])

## Find the integer part of the following array using four different methods:

In [29]:
a = pt.randn((10,), dtype = pt.float32)
a

tensor([ 1.0309,  2.2084,  0.1380,  2.1086, -0.2239, -0.2360, -0.3499, -1.9339,
         0.3697, -1.2809])

In [30]:
pt.floor(a)

tensor([ 1.,  2.,  0.,  2., -1., -1., -1., -2.,  0., -2.])

In [33]:
pt.trunc(a)

tensor([ 1.,  2.,  0.,  2., -0., -0., -0., -1.,  0., -1.])

In [34]:
a.int()

tensor([ 1,  2,  0,  2,  0,  0,  0, -1,  0, -1], dtype=torch.int32)

In [38]:
pt.ceil(a) - 1

tensor([ 1.,  2.,  0.,  2., -1., -1., -1., -2.,  0., -2.])

## Create a vector of 10 values from 0 to 1, both included

In [40]:
vector_custom2 = pt.linspace(0, 1, 10)
vector_custom2

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

## Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [43]:
vector_custom3=pt.linspace(0, 1, 12)[1:-1]
vector_custom3

tensor([0.0909, 0.1818, 0.2727, 0.3636, 0.4545, 0.5455, 0.6364, 0.7273, 0.8182,
        0.9091])

## Subtract the mean of each row of the following matrix

In [44]:
m = pt.rand(3, 3)
m

tensor([[0.4569, 0.6012, 0.8179],
        [0.9736, 0.8175, 0.9747],
        [0.4638, 0.0508, 0.2630]])

In [46]:
m_mean=m.mean(dim=1,keepdim=True)
m_mean

tensor([[0.6253],
        [0.9220],
        [0.2592]])

In [47]:
m_centered=m-m_mean
m_centered

tensor([[-0.1685, -0.0241,  0.1926],
        [ 0.0517, -0.1044,  0.0528],
        [ 0.2046, -0.2084,  0.0037]])

## Add 1,000,000 numbers together using __`torch`__ vectorized operations

In [48]:
large_sum=pt.arange(1,1000001,dtype=pt.float32).sum()
large_sum

tensor(5.0000e+11)

## Create a 4x4 array of the first 16 powers of 3

In [50]:
powers_of_3 = pt.pow(3, pt.arange(16, dtype=pt.float32)).reshape(4, 4)
powers_of_3

tensor([[1.0000e+00, 3.0000e+00, 9.0000e+00, 2.7000e+01],
        [8.1000e+01, 2.4300e+02, 7.2900e+02, 2.1870e+03],
        [6.5610e+03, 1.9683e+04, 5.9049e+04, 1.7715e+05],
        [5.3144e+05, 1.5943e+06, 4.7830e+06, 1.4349e+07]])